version: '3'

services:
  app:
    build: ./node
    ports:
      - 8080:8080
      - 3000:3000
    volumes:
      - ./app:/usr/src/app
      - ./react_app:/usr/src/react_app
      - ./react_todo:/usr/src/react_todo
      - ./react_base:/usr/src/react_base
      - ./react_basic:/usr/src/react_basic
      - ./react_basic_drf:/usr/src/react_basic_drf
      - ./react_design:/usr/src/react_design
      - ./react_ts:/usr/src/react_ts
      - ./react_hooks:/usr/src/react_hooks
      - ./react_chakra:/usr/src/react_chakra
      - ./react_rtk:/usr/src/react_rtk
      - ./react_rtk_tasks:/usr/src/react_rtk_tasks
      - ./redux:/usr/src/redux
      - ./react_stepup:/usr/src/react_stepup
      - ./react_covid:/usr/src/react_covid
      - ./react_covid_api:/usr/src/react_covid_api
    # Tele-TYpewriter、コンテナ起動後に終了させないための設定
    tty: true
    stdin_open: true
    # コンテナが立ち上がらない場合commandをコメントアウトしてコンテナを立ち上げてnpm installを実行する
    command: sh -c "cd react_covid_api && yarn start"
    # ホットリロードの有効化
    environment:
      - CHOKIDAR_USEPOLLING=true