version: "3"

services:
  front:
    container_name: node_next
    build: ./node
    ports:
      - 3000:3000
    volumes:
      - ./front:/usr/src/app
    tty: true
    stdin_open: true
    command: /bin/sh
  back:
    container_name: node_nest
    build: ./node
    ports:
      - 8000:8000
    volumes:
      - ./back:/usr/src/app
    tty: true
    stdin_open: true
    command: /bin/sh
  db:
    container_name: postgresql_nest
    build: ./postgresql
    ports:
      - 5432:5432
    volumes:
      - nestjs-db:/var/lib/postgresql/data
      # - ./postgresql/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_USER=postgres
volumes:
  nestjs-db:
