version: '3'
services:
  selenium:
    container_name: selenium-chrome-br
    image: selenium/standalone-chrome-debug:3.141.59-20210929
    ports:
      - 4444:4444
      - 5900:5900
    shm_size: "2gb"
  test-app:
    container_name: test-app-br
    build: ./test-app
    volumes:
      - ./test-app:/opt/app
    tty: true
