version: '3'
services:
  selenium:
    container_name: selenium-chrome-br
    image: selenium/standalone-chrome-debug:3.141.59-20210929
    ports:
      - 4444:4444
      - 5900:5900
    shm_size: "2gb"
  test-app:
    container_name: test-app-br
    build: ./test-app
    volumes:
      - ./test-app:/opt/app
    tty: true
  db:
    container_name: postgresql_br
    build: ./postgresql
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./postgresql/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_USER=postgres
volumes:
  db-store:
