FROM node:14.16
WORKDIR /usr/src
RUN npm install -g http-server
RUN yarn add redux react-redux
RUN yarn add axios
RUN yarn add redux-thunk
RUN yarn add react-router-dom
RUN yarn add redux-form
RUN yarn add node-sass@^5.0.0