version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - 8080:8080
    volumes:
      - ./nextjs:/usr/src/app
    tty: true
    stdin_open: true
    command: /bin/sh
  backend:
    build: ./backend
    ports:
      - 3000:3000
    volumes:
      - ./nestjs:/usr/src/app
    tty: true
    stdin_open: true
    command: /bin/sh
  db:
    container_name: postgresql_nestjs_nextjs
    build: ./postgresql
    ports:
      - 5432:5432
    volumes:
      - nestjs-nextjs-db:/var/lib/postgresql/data
      # - ./postgresql/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_USER=postgres
volumes:
  nestjs-nextjs-db:
