version: "3"

services:
  frontend:
    build:
      context: ./dockerfile
      dockerfile: Dockerfile_front
    ports:
      - 4000:4000
    volumes:
      - ./frontend:/usr/src/app
    tty: true
    stdin_open: true
    command: /bin/sh
  backend:
    build:
      context: ./dockerfile
      dockerfile: Dockerfile_back
    ports:
      - 3000:3000
    volumes:
      - ./backend:/usr/src/app
    tty: true
    stdin_open: true
    command: /bin/sh
  db:
    build:
      context: ./dockerfile
      dockerfile: Dockerfile_db
    ports:
      - 5432:5432
    volumes:
      - gm-project-db:/var/lib/postgresql/data
      # - ./postgresql/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_USER=postgres
volumes:
  gm-project-db:
