import type { Metadata } from 'next';
import './globals.css';
import { GoogleTagManager } from '@next/third-parties/google';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <header className="bg-blue-200 p-4">Rootヘッダー</header>
        {children}
        {/* GTMタグ挿入 */}
        <GoogleTagManager gtmId="GTM-MFH6LJR8" />
      </body>
    </html>
  );
}
