version: '3'

services:
  app:
    build: ./nuxt
    ports:
      - 3000:3000
    volumes:
      - ./app:/usr/src/app
    tty: true
    stdin_open: true
    command: sh -c "cd  nuxt-blog-app && npm run dev"