version: '3'

services:
  app:
    build: ./node
    ports:
      - 3000:3000
      - 8080:8080
    volumes:
      - ./app:/usr/src/app
    tty: true
    stdin_open: true
    command: /bin/sh
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: rishipippi
      MONGO_INITDB_ROOT_PASSWORD: rishipippi
    ports:
      - "27017:27017"
    volumes:
      - mongodb-store:/data/db
volumes:
  mongodb-store: