version: '3'

services:
  web:
    build: ./python
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./python/src:/src
      - ./python/log:/tmp