version: '3'

services:
  app:
    build: ./vue3
    ports:
      - 8080:8080
    volumes:
      - ./app:/usr/src/app
    tty: true
    stdin_open: true
    command: /bin/sh -c "cd vue_basic/route-basic && npm run serve"