version: '3'

services:
  app:
    build: ./vue3
    ports:
      - 5173:5173
    volumes:
      - ./app:/usr/src/app
    tty: true
    stdin_open: true
    command: /bin/sh -c "cd vue_basic/my-vite && npm run dev"