version: '3'
services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - 8000:80
    container_name: php7.2-trial2
  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    platform: linux/x86_64 #Mac M1
    volumes:
      - php-db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    container_name: mysql5.7-trial2
volumes:
  php-db:
