services:
  app:
    build: ./node
    ports:
      - 3001:3001
    volumes:
      - ./ts:/ts
    tty: true
    stdin_open: true
  react:
    container_name: react
    build: ./node
    ports:
      - 5173:5173
    volumes:
      - ./react:/react
    working_dir: /react
    tty: true
    stdin_open: true
  # next:
  #   container_name: next
  #   build: ./node
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./next:/next
  #   working_dir: /next
  #   tty: true
  #   stdin_open: true
  next-blog:
    container_name: next-blog
    build: ./node
    ports:
      - 3000:3000
    volumes:
      - ./next_blog:/next
    working_dir: /next
    tty: true
    stdin_open: true
  db:
    image: postgres:17
    hostname: db
    env_file:
      - ./.env
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
