services:
  app:
    build: ./node
    ports:
      - 3001:3001
    volumes:
      - ./ts:/ts
    tty: true
    stdin_open: true

  react:
    container_name: react
    build: ./node
    ports:
      - 5173:5173
    volumes:
      - ./react:/react
    working_dir: /react
    tty: true
    stdin_open: true
  next:
    container_name: next
    build: ./node
    ports:
      - 3000:3000
    volumes:
      - ./next:/next
    working_dir: /next
    tty: true
    stdin_open: true